const CATEGORIES=['Study','Recovery','Maintenance','Exploration','Fun','Life'];
const STATES=['bored','tired','restless','avoidant','focused','curious','low mood'];
const ENERGIES=['low','medium','high'];
const TIMES=[2,10,25,60];
const REASONS=['done','bored','too hard','tired','feels meaningless','avoiding','interrupted','wrong pick'];
const KEY='determinationAnchor.v1';
const $=s=>document.querySelector(s); const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);
const now=()=>new Date().toISOString(); const today=()=>new Date().toISOString().slice(0,10);
const starter=[
['IELTS Reading P2','Study','medium',[25,60],['focused','avoidant'],'Open one passage and underline the first question stem.','Complete one timed passage section.','Check answers and write one trap pattern.','Builds exam stamina without waiting for motivation.','Tea after review',3,['ielts','reading']],
['IELTS Listening clip review','Study','low',[10,25],['tired','focused'],'Play one 60-second clip and catch keywords.','Review one clip twice and note missed words.','Write three missed sounds or phrases.','Sharpens listening through small repairs.','Save a favorite phrase',2,['ielts','listening']],
['Vocabulary active recall','Study','low',[2,10,25],['bored','avoidant'],'Pick five words and hide the answers.','Recall five words before checking.','Mark known, shaky, and missed words.','Tiny recall beats passive rereading.','One minute of music',1,['vocabulary']],
['Science concept repair','Study','medium',[10,25],['curious','focused'],'Write the concept name and one confusion.','Repair one weak concept with notes or a sketch.','Explain it in three plain sentences.','Turns vague anxiety into a fixable gap.','Add a victory mark',3,['science']],
['10-minute walk','Recovery','low',[10,25],['restless','low mood','tired'],'Put shoes on or stand at the door.','Walk for the selected time without optimizing.','Return with one word for how you feel.','Movement changes state before thoughts cooperate.','Fresh drink',1,['walk','body']],
['Shower reset','Recovery','low',[10,25],['tired','low mood','restless'],'Start the water or gather towel.','Take a simple reset shower.','Clean clothes or fresh face complete it.','A body reset can restart the whole cockpit.','Comfortable clothes',2,['reset']],
['Clean desk','Maintenance','medium',[2,10,25],['avoidant','restless'],'Move one object to its home.','Clear the visible work zone.','Desk has one open landing area.','Removes friction from the next good choice.','Light a lamp',2,['space']],
['Drink water / make tea','Recovery','low',[2,10],['tired','low mood','avoidant'],'Fill a glass or put kettle on.','Drink water or make tea.','Cup is finished or beside you.','Basic care is an anchor, not a detour.','Warm hands pause',1,['hydration']],
['Read one article','Exploration','medium',[10,25],['curious','bored'],'Open one saved article and read the title.','Read one article with no rabbit holes.','Write one takeaway.','Feeds curiosity with a boundary.','Share/save one quote',2,['reading']],
['Watch one video with stop timer','Fun','low',[10,25],['bored','tired'],'Choose one video and set a stop timer.','Watch one video only.','Timer ends and tab closes.','Controlled fun prevents drift.','Enjoy guilt-free',2,['video','controlled fun']],
['Play one timed game session','Fun','medium',[10,25],['bored','restless'],'Open game and set timer first.','Play one timed session.','Stop when timer rings.','Fun is safer with edges.','Record score',3,['game','controlled fun']],
['Plan tomorrow','Life','low',[10,25],['avoidant','focused'],'Write tomorrow at the top of a note.','Choose three anchors for tomorrow.','Top three are visible.','Future-you needs fewer decisions.','Close the day',2,['planning']],
['Tiny journal note','Recovery','low',[2,10],['low mood','restless','tired'],'Write “Right now I notice…”','Write three honest lines.','Three lines exist; no fixing required.','Names the state so it stops steering silently.','Deep breath',1,['journal']],
['Stretch for 5 minutes','Recovery','low',[10],['restless','tired'],'Stand up and roll shoulders once.','Stretch gently for five minutes.','Body feels at least 1% different.','Loosens stuck energy without a big plan.','Water sip',1,['body']],
['Organize downloads folder','Maintenance','medium',[10,25],['bored','avoidant'],'Open Downloads and sort by date.','Delete or file ten items.','Ten items handled.','Small order creates visible momentum.','Clean desktop glance',2,['digital']]
].map(a=>({id:uid(),title:a[0],category:a[1],energyRequired:a[2],timeOptions:a[3],suitableStates:a[4],minimumStartStep:a[5],standardVersion:a[6],completionDefinition:a[7],whyItMatters:a[8],rewardSuggestion:a[9],frictionLevel:a[10],tags:a[11],createdAt:now(),updatedAt:now()}));
let db=load(), timerInt=null;
function load(){let raw=localStorage.getItem(KEY); if(raw) return JSON.parse(raw); return {activities:starter,sessions:[],logs:[]};}
function save(){localStorage.setItem(KEY,JSON.stringify(db)); render();}
function activeSession(){return db.sessions.find(s=>s.status==='active');}
function act(id){return db.activities.find(a=>a.id===id);} function mins(s){return Math.max(0,Math.round(((s.endedAt?new Date(s.endedAt):new Date())-new Date(s.startedAt))/60000));}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function setTab(id){document.querySelectorAll('.tab,.panel').forEach(e=>e.classList.remove('active'));document.querySelector(`[data-tab=${id}]`).classList.add('active');$('#'+id).classList.add('active');render();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
function score(a,q,mode='main'){let s=0;if(a.suitableStates.includes(q.state))s+=4;if(a.energyRequired===q.energy)s+=3;if(a.timeOptions.includes(+q.time))s+=2;if(q.direction==='Surprise me'||a.category===q.direction)s+=3;s+=6-a.frictionLevel;if(mode==='tiny')s+=a.energyRequired==='low'?4:0,s+=6-a.frictionLevel;if(mode==='recovery')s+=a.category==='Recovery'?8:0;if(mode==='fun')s+=a.category==='Fun'?8:0;return s+Math.random()/10}
function recommend(q,mode='main',exclude){return [...db.activities].filter(a=>a.id!==exclude).sort((a,b)=>score(b,q,mode)-score(a,q,mode))[0];}
function start(activityId,q,mode){let s={id:uid(),activityId,mode,selectedState:q.state,selectedEnergy:q.energy,selectedTime:+q.time,desiredDirection:q.direction,startedAt:now(),endedAt:null,status:'active',switchReason:'',note:'',createdAt:now(),updatedAt:now()};let cur=activeSession(); if(cur){cur.status='switched';cur.endedAt=now();cur.switchReason='new anchor';cur.updatedAt=now()} db.sessions.push(s);save();setTab('current');toast('Anchor started')}
function endActive(status,reason='done',note){let s=activeSession(); if(!s)return; s.status=status;s.endedAt=now();s.switchReason=reason;s.note=note??s.note;s.updatedAt=now(); if(status!=='completed') db.logs.push({id:uid(),sessionId:s.id,activityId:s.activityId,reason,createdAt:now()}); save();}
function dashboard(){let cur=activeSession(), comp=db.sessions.filter(s=>s.status==='completed'&&s.endedAt?.slice(0,10)===today()).length, sw=db.logs.filter(l=>l.createdAt.slice(0,10)===today()).length;let common=top(db.logs.map(l=>l.reason))[0]?.[0]||'None yet';return `<div class="grid"><div class="card span8"><h2>Current Anchor</h2>${cur?anchorMini(cur):'<p class="muted">No active anchor. Choose a replacement action before the vacuum grows.</p>'}<div class="actions big-actions"><button class="btn primary" onclick="setTab('anchor')">Anchor Me</button><button class="btn" onclick="quick('bored')">I’m Bored</button><button class="btn" onclick="quick('avoidant')">I’m Avoiding</button><button class="btn warn" onclick="openSwitch()">Switch Anchor</button><button class="btn good" onclick="noVacuum()">I Decided Not To Do Something</button></div></div><div class="card span4"><h2>Today</h2><p class="metric">${comp}</p><p class="muted">completed anchors</p><p class="metric">${sw}</p><p class="muted">switched anchors</p><p>Common switch: <span class="chip">${common}</span></p></div><div class="card span6"><h2>Most effective recent anchors</h2>${list(effective().map(a=>`<b>${a.title}</b><br><span class="muted">${a.category} · ${a.rewardSuggestion}</span>`))}</div><div class="card span6"><h2>Recent activity</h2>${list(db.sessions.slice(-6).reverse().map(s=>`${act(s.activityId)?.title||'Deleted activity'} <span class="chip">${s.status}</span><br><span class="muted">${new Date(s.createdAt).toLocaleString()}</span>`))}</div></div>`}
function anchorFlow(q={state:'bored',energy:'low',time:10,direction:'Surprise me'}){let main=recommend(q,'main'), tiny=recommend(q,'tiny',main?.id), esc=recommend(q,'fun',main?.id)||recommend(q,'recovery');return `<div class="card"><h2>Anchor Me</h2><p class="muted">Four quick questions. Then choose Main, Tiny, or Escape Anchor.</p><div class="form-grid">${sel('state','Current state',STATES,q.state)}${sel('energy','Energy',ENERGIES,q.energy)}${sel('time','Available time',TIMES,q.time)}${sel('direction','Desired direction',[...CATEGORIES,'Surprise me'],q.direction)}</div><br><button class="btn primary" onclick="readAnchorForm()">Recommend anchors</button></div><div class="grid">${recCard('Main Anchor',main,q,'main')} ${recCard('Tiny Anchor',tiny,q,'tiny')} ${recCard('Escape Anchor',esc,q,'escape')}</div>`}
function recCard(label,a,q,mode){if(!a)return '';return `<div class="card span4 rec ${mode==='main'?'main':''}"><p class="eyebrow">${label}</p><h3>${a.title}</h3><p>${a.whyItMatters}</p><p><b>Tiny Start:</b> ${a.minimumStartStep}</p><p><b>Complete:</b> ${a.completionDefinition}</p><p><span class="chip">${q.time} min</span> <span class="chip">friction ${a.frictionLevel}/5</span></p><button class="btn primary" onclick='start("${a.id}",${JSON.stringify(q)},"${mode}")'>Start</button></div>`}
function current(){let s=activeSession(); if(!s)return `<div class="card"><h2>Current Anchor</h2><p class="muted">No active anchor.</p><button class="btn primary" onclick="setTab('anchor')">Anchor Me</button></div>`; let a=act(s.activityId); setTimeout(runTimer,0);return `<div class="card"><p class="eyebrow">Current Mode · ${s.mode}</p><h2>${a.title}</h2><p><span class="chip">${a.category}</span> <span class="chip">${s.selectedTime} minutes</span></p><p>${a.whyItMatters}</p><h3>Tiny Start</h3><p>${a.minimumStartStep}</p><h3>Completion definition</h3><p>${a.completionDefinition}</p><div class="timer" id="timer">--:--</div><label>Notes<textarea id="sessionNote">${s.note||''}</textarea></label><br><div class="actions"><button class="btn good" onclick="completeAnchor()">Complete</button><button class="btn warn" onclick="openSwitch('switched')">Switch</button><button class="btn danger" onclick="openSwitch('abandoned')">Abandon</button></div></div>`}
function runTimer(){clearInterval(timerInt);let s=activeSession(), el=$('#timer'); if(!s||!el)return;let end=+new Date(s.startedAt)+s.selectedTime*60000;timerInt=setInterval(()=>{let left=Math.max(0,end-Date.now()),m=String(Math.floor(left/60000)).padStart(2,'0'),sec=String(Math.floor(left/1000)%60).padStart(2,'0');el.textContent=`${m}:${sec}`},500)}
function completeAnchor(){let n=$('#sessionNote')?.value;endActive('completed','done',n);toast('Anchor complete')}
function bank(){return `<div class="card"><div class="actions"><h2 style="flex:1">Activity Bank</h2><button class="btn primary" onclick="editActivity()">Add activity</button></div><div class="form-grid">${sel('fc','Category',['All',...CATEGORIES],window.fc||'All')}${sel('fe','Energy',['All',...ENERGIES],window.fe||'All')}${sel('ftime','Time',['All',...TIMES],window.ftime||'All')}${sel('fs','State',['All',...STATES],window.fs||'All')}<label>Tag search<input id="ft" oninput="window.ft=this.value;render()" value="${window.ft||''}" placeholder="tag or title"></label></div></div><div class="list">${filteredActs().map(a=>`<div class="item"><h3>${a.title}</h3><p><span class="chip">${a.category}</span> <span class="chip">${a.energyRequired}</span> <span class="chip">${a.timeOptions.join('/')} min</span></p><p>${a.minimumStartStep}</p><div class="actions"><button class="btn" onclick="editActivity('${a.id}')">Edit</button><button class="btn danger" onclick="delActivity('${a.id}')">Delete</button></div></div>`).join('')}</div>`}
function logView(){return `<div class="card"><h2>Switch Log</h2>${list(db.logs.slice().reverse().map(l=>`${act(l.activityId)?.title||'Deleted activity'} <span class="chip">${l.reason}</span><br><span class="muted">${new Date(l.createdAt).toLocaleString()}</span>`))}</div>`}
function stats(){let comp=db.sessions.filter(s=>s.status==='completed'), week=comp.filter(s=>Date.now()-new Date(s.endedAt)<7*864e5).length;return `<div class="grid">${metric('Completed today',comp.filter(s=>s.endedAt?.slice(0,10)===today()).length)}${metric('Completed this week',week)}${metric('Switch count',db.sessions.filter(s=>s.status==='switched').length)}${metric('Abandon count',db.sessions.filter(s=>s.status==='abandoned').length)}<div class="card span6"><h2>Most common switch reasons</h2>${table(top(db.logs.map(l=>l.reason)))}</div><div class="card span6"><h2>Most used activities</h2>${table(top(db.sessions.map(s=>act(s.activityId)?.title||'Deleted')))}</div><div class="card span6"><h2>Best low-energy anchors</h2>${list(effective(a=>a.energyRequired==='low').map(a=>a.title))}</div><div class="card span6"><h2>Completion rate by category</h2>${table(CATEGORIES.map(c=>[c,rate(c)]))}</div><div class="card"><h2>Time spent by category</h2>${table(CATEGORIES.map(c=>[c,db.sessions.filter(s=>act(s.activityId)?.category===c&&s.status==='completed').reduce((n,s)=>n+mins(s),0)+' min']))}</div></div>`}
function dataView(){return `<div class="card"><h2>Data</h2><p class="muted">Privacy note: all data is stored locally in this browser and is not uploaded.</p><div class="actions"><button class="btn primary" onclick="exportData()">Export JSON</button><label class="btn">Import JSON<input type="file" accept="application/json" hidden onchange="importData(event)"></label><button class="btn danger" onclick="clearData()">Clear local data</button></div><pre class="item">Activities: ${db.activities.length}\nSessions: ${db.sessions.length}\nSwitch logs: ${db.logs.length}</pre></div>`}
function render(){if($('#dashboard.active'))$('#dashboard').innerHTML=dashboard(); if($('#anchor.active'))$('#anchor').innerHTML=anchorFlow(window.lastQ); if($('#current.active'))$('#current').innerHTML=current(); if($('#bank.active'))$('#bank').innerHTML=bank(); if($('#log.active'))$('#log').innerHTML=logView(); if($('#stats.active'))$('#stats').innerHTML=stats(); if($('#data.active'))$('#data').innerHTML=dataView();}
function sel(id,label,opts,val){return `<label>${label}<select id="${id}" onchange="render()">${opts.map(o=>`<option ${String(o)===String(val)?'selected':''}>${o}</option>`).join('')}</select></label>`}
function readAnchorForm(){window.lastQ={state:$('#state').value,energy:$('#energy').value,time:+$('#time').value,direction:$('#direction').value};render()}
function quick(state){window.lastQ={state,energy:state==='tired'?'low':'medium',time:10,direction:'Surprise me'};setTab('anchor')}
function noVacuum(){let what=prompt('What did you decide not to do?')||'an avoided option', why=prompt('Why?')||'not right now';let q={state:'avoidant',energy:'low',time:10,direction:'Surprise me'};setTab('anchor');$('#anchor').innerHTML=`<div class="card"><p class="eyebrow">No Vacuum Rule</p><h2>You created a vacuum. Choose a replacement anchor.</h2><p class="muted">Not doing: ${esc(what)} · Why: ${esc(why)}</p></div><div class="grid">${recCard('Recovery Anchor',recommend(q,'recovery'),q,'recovery')}${recCard('Productive Tiny Anchor',recommend({...q,direction:'Study'},'tiny'),q,'tiny')}${recCard('Controlled Fun',recommend({...q,direction:'Fun'},'fun'),q,'fun')}</div>`}
function openSwitch(status='switched'){let s=activeSession(); if(!s){toast('No active anchor');return} $('#switchDialog').innerHTML=`<div class="modal-inner"><h2>Switch Ritual</h2><p class="muted">Name the reason, then choose the next anchor. No vacuum.</p><div class="list">${REASONS.map(r=>`<button class="btn" onclick="switchReason('${status}','${r}')">${r}</button>`).join('')}</div></div>`;$('#switchDialog').showModal()}
function switchReason(status,reason){let old=activeSession(), q={state:old.selectedState,energy:old.selectedEnergy,time:reason==='avoiding'?2:old.selectedTime,direction:old.desiredDirection}; if(reason==='too hard') q.energy='low'; if(reason==='tired') q.direction='Recovery'; if(reason==='bored') q.state='bored'; endActive(status,reason,$('#sessionNote')?.value); $('#switchDialog').close(); window.lastQ=q; setTab('anchor'); toast('Pick the replacement anchor')}
function editActivity(id){let a=id?act(id):{title:'',category:'Study',energyRequired:'low',timeOptions:[10],suitableStates:['bored'],minimumStartStep:'',standardVersion:'',completionDefinition:'',whyItMatters:'',rewardSuggestion:'',frictionLevel:2,tags:[]};$('#activityDialog').innerHTML=`<form class="modal-inner" method="dialog" onsubmit="saveActivity('${id||''}');return false"><h2>${id?'Edit':'Add'} activity</h2><div class="form-grid"><label>Title<input id="at" value="${esc(a.title)}" required></label>${sel('ac','Category',CATEGORIES,a.category)}${sel('ae','Energy',ENERGIES,a.energyRequired)}<label>Times CSV<input id="ati" value="${a.timeOptions.join(',')}"></label><label>States CSV<input id="as" value="${a.suitableStates.join(',')}"></label><label>Friction 1-5<input id="af" type="number" min="1" max="5" value="${a.frictionLevel}"></label></div><label>Minimum start step<textarea id="ams">${esc(a.minimumStartStep)}</textarea></label><label>Standard version<textarea id="av">${esc(a.standardVersion)}</textarea></label><label>Completion definition<textarea id="acd">${esc(a.completionDefinition)}</textarea></label><label>Why it matters<textarea id="aw">${esc(a.whyItMatters)}</textarea></label><label>Reward suggestion<input id="ar" value="${esc(a.rewardSuggestion)}"></label><label>Tags CSV<input id="ag" value="${a.tags.join(',')}"></label><br><button class="btn primary">Save activity</button></form>`;$('#activityDialog').showModal()}
function saveActivity(id){let a=id?act(id):{id:uid(),createdAt:now()};Object.assign(a,{title:$('#at').value,category:$('#ac').value,energyRequired:$('#ae').value,timeOptions:csv($('#ati').value).map(Number).filter(Boolean),suitableStates:csv($('#as').value),minimumStartStep:$('#ams').value,standardVersion:$('#av').value,completionDefinition:$('#acd').value,whyItMatters:$('#aw').value,rewardSuggestion:$('#ar').value,frictionLevel:+$('#af').value,tags:csv($('#ag').value),updatedAt:now()});if(!id)db.activities.push(a);$('#activityDialog').close();save()}
function delActivity(id){if(confirm('Delete this activity?')){db.activities=db.activities.filter(a=>a.id!==id);save()}}
function filteredActs(){let c=$('#fc')?.value||window.fc||'All',e=$('#fe')?.value||window.fe||'All',tm=$('#ftime')?.value||window.ftime||'All',st=$('#fs')?.value||window.fs||'All',t=($('#ft')?.value||window.ft||'').toLowerCase();window.fc=c;window.fe=e;window.ftime=tm;window.fs=st;return db.activities.filter(a=>(c==='All'||a.category===c)&&(e==='All'||a.energyRequired===e)&&(tm==='All'||a.timeOptions.includes(+tm))&&(st==='All'||a.suitableStates.includes(st))&&(!t||a.title.toLowerCase().includes(t)||a.tags.join(' ').toLowerCase().includes(t)))}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='determination-anchor-data.json';a.click();URL.revokeObjectURL(u)}
function importData(e){let f=e.target.files[0]; if(!f)return; f.text().then(t=>{let incoming=JSON.parse(t); if(!incoming.activities||!incoming.sessions)throw Error('Invalid data'); db={activities:incoming.activities,sessions:incoming.sessions,logs:incoming.logs||[]};save();toast('Data imported')}).catch(()=>toast('Import failed'))}
function clearData(){if(confirm('Clear all local data?')){localStorage.removeItem(KEY);db=load();save()}}
function top(arr){let m={};arr.filter(Boolean).forEach(x=>m[x]=(m[x]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,8)}
function effective(filter=()=>true){return db.activities.filter(filter).map(a=>({a,n:db.sessions.filter(s=>s.activityId===a.id&&s.status==='completed').length})).sort((x,y)=>y.n-x.n).filter(x=>x.n||filter!==undefined).slice(0,5).map(x=>x.a)}
function rate(c){let all=db.sessions.filter(s=>act(s.activityId)?.category===c).length, done=db.sessions.filter(s=>act(s.activityId)?.category===c&&s.status==='completed').length;return all?Math.round(done/all*100)+'%':'0%'}
function metric(k,v){return `<div class="card span4"><p class="muted">${k}</p><p class="metric">${v}</p></div>`} function list(a){return a.length?`<div class="list">${a.map(x=>`<div class="item">${x}</div>`).join('')}</div>`:'<p class="muted">Nothing logged yet.</p>'} function table(rows){return rows.length?`<table>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td></tr>`).join('')}</table>`:'<p class="muted">Nothing yet.</p>'}
function anchorMini(s){let a=act(s.activityId);return `<div class="item"><h3>${a?.title}</h3><p>${a?.minimumStartStep}</p><button class="btn primary" onclick="setTab('current')">Open Current Anchor</button></div>`}
function csv(v){return v.split(',').map(x=>x.trim()).filter(Boolean)} function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js');
render();
